### ISSUE TITLE
FIXED: Node v10 Error: node_contextify.cc Assertion `args[1]->IsString()' failed

### ISSUE THREAD

**Issue by BobbyBabes** [electric-eloquence/fepper#12]
After installing `fepper-cli` I run `npm install` and am presented with the following error.
Any ideas how to resolve this ?

After the error, when I search for `source` in the test project, I find 2 directories :
```
[bobbybabes@ladyluck 4.4.23 fepper-test]# find . -iname 'source'
./node_modules/fepper/excludes/profiles/main/source
./node_modules/fepper/excludes/profiles/base/source
```

The error :

```
[bobbybabes@ladyluck 4.4.23 fepper-test]# npm install

> @0.4.2 postinstall /home/bobbybabes/dev/web/fepper-test
> node run/install.js

[15:56:13] Working directory changed to ~/dev/web/fepper-test/node_modules/fepper
gulp[29679]: ../src/node_contextify.cc:635:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x557228e10d61 node::Abort() [gulp]
 2: 0x557228e10e5b  [gulp]
 3: 0x557228e406c4 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0x55722904ab1f  [gulp]
 5: 0x55722904b21f  [gulp]
 6: 0xc8f4cc841bd 
fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir 'source'
    at Object.readdirSync (fs.js:759:3)
    at Object.<anonymous> (/home/bobbybabes/dev/web/fepper-test/run/install.js:71:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @0.4.2 postinstall: `node run/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @0.4.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bobbybabes/.npm/_logs/2018-07-23T13_56_14_244Z-debug.log
```

![fepper-npm-install-error_screenshot_20180723_163436](https://user-images.githubusercontent.com/22870070/43083487-f013d4cc-8e96-11e8-9c38-a5273e0d601e.png)

**Comment by e2tha-e** [comment]
@BobbyBabes
Thanks for trying out Fepper!
 
I guess the first question is what Node version are you using? Fepper's minimum is 8.5.0, which is necessary for running `fs.copyFileSync`.

If the Node version isn't the issue, please tell me more about your OS and shell.

**Comment by BobbyBabes** [comment]
OS is Arch Linux on kernel 4.17.8.

```Shell
[bobbybabes@ladyluck 4.4.23 ~]# echo -e '\n'; node -v; echo -e '\n\n'; npm -v; echo -e '\n\n'; bash --version; echo -e '\n\n';uname --all; echo -e '\n';


v10.7.0



6.2.0



GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.



Linux ladyluck 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux
```

![fepper-npm-install-error_screenshot_20180724_163529](https://user-images.githubusercontent.com/22870070/43145518-d420e934-8f5f-11e8-8ffa-976366cd3e8d.png)

**Comment by e2tha-e** [comment]
Ok. I'll try it with that Node and NPM version, and create a VM with that Linux disto if necessary.

**Comment by e2tha-e** [comment]
I can replicate this, and this appears to be a greater issue within the Node and Gulp ecosystems:
https://github.com/nodejs/node/issues/20325
https://github.com/nodejs/node/issues/20285

Not sure why they closed these issues given that the only recommended workaround is to downgrade Node to below v10.0.0.

That's all I can recommend for now, until (unless?) I can figure out a workaround for v10+. I'll keep this issue open until I fix it or give up.

**Comment by BobbyBabes** [comment]
Hey, thanks for looking into this. If it's upstream, and only occurs with a combination of Node and Gulp, please don't spend (too much or more) time on fixing it. After the test that I had planned, I was going to replace Gulp anyway.
Also, so far it looks that I'm the only one reporting this.

I install Node as an Arch Linux package.
So, for my planned test, I will have to find out how to downgrade Node temporarily.  Shouldn't be too hard. I do know how to prevent a package from being updated/upgraded (for after the downgrade).
Or I have to uninstall the Arch Node package, and then install a downloaded pre-v10 Node manually, and forfeit the package manager checking package dependencies while testing Fepper.

**Comment by BobbyBabes** [comment]
I downgraded the nodejs package to v9.11.1 from the package manager's cache.
And all is OK now. `npm install` ran without issues. And the `fp` command displayed the `http://localhost:3000/success` page in the browser.
Thanks. I'm going to give this a workout.

I'm going to treat this newly created directory with Fepper as a jump start project folder (copy it to start new tests or projects). And I'm going to upgrade Node again.

**Comment by BobbyBabes** [comment]
Downgrading is not necessary. I installed [nvm, from the Arch User Repository](https://aur.archlinux.org/packages/nvm/). Its Github repo is here : [https://github.com/creationix/nvm](https://github.com/creationix/nvm) Now I can install and use any version of node and npm. Or use the version (v10.8.0) that was installed with pacman from the official Arch repo.

P.S.
With another project that uses vinyl-fs, contextify, and natives (Gulp 3 on Node v10) there were assertion errors, binding issues, and unsupported runtime errors, after the downgrade.
Uninstalling then reinstalling the modules did not fix anything. I had to delete node_modules and reinstall (with the downgraded Node and Npm). I guess because during installation these modules were compiled against (with bindings to) the newer Node version.

**Comment by e2tha-e** [comment]
I unintentionally fixed this bug as of v0.5.0 through routine maintenance. It turns out that this bug was caused by the `gulp-rename` devDependency. Having removed `gulp-rename`, Fepper installs and works correctly in Node v10+.

I'm leaving this issue open for reference for the general gulp community.

**Comment by e2tha-e** [comment]
Changing title to help direct searches regarding this error here.

**Comment by e2tha-e** [comment]
[Why you may want to remain on gulp 3 and how to do so securely.](https://github.com/electric-eloquence/gulp/blob/v3-lts/docs/why-gulp-3.md)
