### ISSUE TITLE
UI customisation

### ISSUE THREAD

**Issue by BobbyBabes** [electric-eloquence/fepper#13]
Did [UI Customization](https://github.com/electric-eloquence/fepper#ui-customization) replace [styleguidekit-assets-default](https://github.com/pattern-lab/styleguidekit-assets-default) ?

**Comment by e2tha-e** [comment]
@BobbyBabes Yes. Since hard-forking from Pattern Lab for Node (which I contributed to in the early days), I have not really stayed on top of its architecture of dependencies, so I can't comment much on the differences of approach.

If you want to customize the "styleguide," or "UI," you can do so with complete control. You might need to get familiar with React, but that seems the norm in JS-land these days.

As for questions like "why React?" and "why functional programming?," they're so both core code and custom code can receive updates without trampling over each other.

Please ask any other questions here. I would love to see real-world UI customization.

**Comment by BobbyBabes** [comment]
I need to look further into this (workload, I'm not familiar with React yet) because in two current Patternlab projects I have used the styleguidekit assets, and in a few older projects (started in Jan 2017) I used `./source/css/pattern-scaffolding.css`. because the styleguide-assets were in limbo at the time.

**Comment by e2tha-e** [comment]
As an FYI, `./source/_styles/pattern-scaffolding.css` will be re-introduced in the next release. I'm maintaining the canonical Pattern Lab filename, but am trying to encourage React-style componentized UI building, as opposed to monolithic scaffolding. `pattern-scaffolding.css` won't automatically appear with an upgrade, so you might need to import to or from a fresh install of the next release.

**Comment by BobbyBabes** [comment]
I was actually trying to get away from `./source/css/pattern-scaffolding.css` because it wasn't the official/endorsed way of restyling the UI, and it would be overwritten during updates of patternlab gulp. And I had to copy back in my changes. When they started updating the styleguidekit assets again (the official/endorsed way), I started using that in new projects. And planned the same for the older projects.  This all is of course not relevant to Fepper because of the change in UI customisation.

Also, I planned to use Sass or Less (either) instead of plain css for scaffolding, and just overwrite `./source/css/pattern-scaffolding.css` altogether.Which would probably not work just like that, for Fepper's `pattern-scaffolding.css` because of the connection to React, I guess.
I'll see how it goes.

**Comment by e2tha-e** [comment]
@BobbyBabes  [Fepper v0.5.1](https://github.com/electric-eloquence/fepper/releases/latest) has been released! It has full support for `./source/_styles/pattern-scaffolding.css`. This will not get overwritten during updates.

**Comment by BobbyBabes** [comment]
I'll check it out. Thanks!

**Comment by e2tha-e** [comment]
Regarding Sass, Less, etc: https://github.com/electric-eloquence/fepper/issues/14

**Comment by e2tha-e** [comment]
Closing since GitHub now has a [Discussions section](https://github.com/electric-eloquence/fepper/discussions), which is more appropriate for questions. The Issues section will be for bug reports, which are meant to be closed eventually.
